### PR TITLE
Added ConsumerName to the loinc loader.

### PR DESCRIPTION
**Pull request by frankjtao**

### CODE REVIEW

**Review by jamesagnew — APPROVED** [review]

**Comment by jamesagnew** [comment]
Hi @frankjtao - This looks good. One request, can you add a changelog before we merge?

**Comment by frankjtao** [comment]
> Hi @frankjtao - This looks good. One request, can you add a changelog before we merge?
@jamesagnew I will add changelog after LinguisticVariants is added. And

**Comment by jamesagnew** [comment]
@frankjtao ah ok - do you not want this merged then? Just confirming, since it has been closed without a merge.

**Comment by frankjtao** [comment]
> @frankjtao ah ok - do you not want this merged then? Just confirming, since it has been closed without a merge.

@jamesagnew Sorry, clicked the wrong button.  Will do the merge after LinguisticVariants is implemented.

**Comment by frankjtao** [comment]
> > @frankjtao ah ok - do you not want this merged then? Just confirming, since it has been closed without a merge.
> 
> @jamesagnew Sorry, clicked the wrong button. Will do the merge after LinguisticVariants is implemented.

@jamesagnew I have changed mind, will merge this PR.

**Pull request merged**
