### PR TITLE
Delete hapi_fhir_banner_right.png

### PR DESCRIPTION
**Pull request by Kusuma16**

### CODE REVIEW

**Comment by jamesagnew** [comment]
Hi @Kusuma16 - I'm not clear on what this PR is about - We use the image you're trying to delete in the testpage overlay module. Unfortunately we can't merge this.

**Comment by Kusuma16** [comment]
Iam sorry for this sir

**Comment by jamesagnew** [comment]
@Kusuma16 no problem :)

**Comment by Kusuma16** [comment]
Iam a beginner sir. and accidently I am studying to modify the logo of the HAPI FHIR. but i havent find the way :(

**Pull request closed without merging**
