### PR TITLE
4379: allow interceptor annotation on methods

### PR DESCRIPTION
**Pull request by doumdoum**
Hi,
Fixing https://github.com/hapifhir/hapi-fhir/issues/4379

Regards,

/DV

### CODE REVIEW

**Comment by doumdoum** [comment]
Hello, kind reminder

**Comment by doumdoum** [comment]
Hello, any news regarding this PR ?

**Comment by doumdoum** [comment]
Hello, any news regarding this PR ?

**Comment by doumdoum** [comment]
Hi, kind reminder...

**Comment by doumdoum** [comment]
Hi, any news regarding this PR ?

**Comment by jamesagnew** [comment]
Hi @doumdoum -

Thanks for the contribution. I'm concerned though that this could be confusing to users if we allow this at the method level, since HAPI FHIR doesn't actually look at it when used at the method level. E.g. a user might do something like:

```java
@Interceptor(order=5)
@Hook(Pointcut.FOO)
public void blah() { }
```

..and then expect the order to be respected, when it won't be. At a minimum the javadoc should probably be updated to point out that the annotation is purely a marker when used at method level, and the properties will be ignored.

**Comment by doumdoum** [comment]
> Hi @doumdoum -
> 
> Thanks for the contribution. I'm concerned though that this could be confusing to users if we allow this at the method level, since HAPI FHIR doesn't actually look at it when used at the method level. E.g. a user might do something like:
> 
> ```java
> @Interceptor(order=5)
> @Hook(Pointcut.FOO)
> public void blah() { }
> ```
> 
> ..and then expect the order to be respected, when it won't be. At a minimum the javadoc should probably be updated to point out that the annotation is purely a marker when used at method level, and the properties will be ignored.

Hi @jamesagnew, sorry for this late response. 
If the interceptor is registered through the registerInterceptor method then order is respected no ?
Should it be sufficient to mention that order is respected as long as interceptor is registered ?

**Pull request merged**
