### PR TITLE
Extracts Caching Libraries into Service Loaders (Caffeine -> Java, Guava -> Android)

### PR DESCRIPTION
**Pull request by vitorpamplona**
### Background

[Caffeine 3.0+ does not plan to support Android](https://github.com/ben-manes/caffeine/issues/763). The 3.0 version requires a `java.lang.System.getLogger` method from the [JEP-264: Platform Logging API](https://openjdk.java.net/jeps/264) to redirect logs to `slf4j`. Unfortunately, Android has not provided a `System.getLogger` interface yet. This means a HAPI migration to Caffeine 3.0+ will simply crash in runtime on Android. 

### Solution

Abstract the Caching function, remove direct dependencies on Caffeine, and build an Android-friendly alternative. 

1. This PR establishes a new Caching structure via ServiceLoaders in 4 new maven modules: 
   - `hapi-fhir-cache`: Cache service loader interfaces and factory methods. 
   - `hapi-fhir-cache-guava`: Delegator classes to Guava (ideal for Android)
   - `hapi-fhir-cache-caffeine`: Delegator classes to Caffeine (current implementation) 
   - `hapi-fhir-cache-testing`: Utility module to quickly alternate between `guava` and `caffeine` and run the project's test cases on.

2. All modules dependent on `caffeine` now depend on `hapi-fhir-cache` directly. Users must choose a caching implementation by also importing `hapi-fhir-cache-caffeine`  or `hapi-fhir-cache-guava`. If none is present, the following error message will be displayed: `No Cache Service Providers found. Choose between hapi-fhir-cache-caffeine (Default) and hapi-fhir-cache-guava (Android)`

3. `hapi-fhir-cache-guava` contains brand new Cache and LoadingCache implementations that mimic Caffeine's behavior completely and it's ideal for the use of HAPI on Android. In my tests, it fully replaces Caffeine for the needs of this project. 

Closes: #2444, Helps: #3690

### CODE REVIEW

**Comment by ben-manes** [comment]
Just want to make sure this wasn't forgotten in the discussion. If the [cache-api](https://github.com/Xanthic/cache-api) project fit your needs, it might be a good way for you and others to collaborate. It may not and I am not familiar with it or the developers, but an fyi in case that avoids duplication of efforts.

**Comment by vitorpamplona** [comment]
Thank you, Ben! I didn't know the project existed. Maybe we can collaborate with them in the future. 

At a first glance, it does a similar job. However, the cache-api does not standardize the interface among all implementations and it doesn't offer a provider for the `LoadingCache` class. This makes testing for all implementations really difficult. There are behavioral differences between Caffeine and Guava that need to be sorted out by the Delegator. You can see them in the `Cache.get` method in the Guava module that it: 

1. Has to wrap ExecutionExeptions as RuntimeExeptions 
2. Has to unwrap UncheckedExecutionException to expose the original Exception 
3. Has to not throw exceptions when the CacheLoader returns null

These are needed to completely match Caffeine's API. 

The CacheDelegator ends up looking like this: 

```java
try {
	return cache.get(key, () -> mappingFunction.apply(key));
} catch (ExecutionException e) {
	e.printStackTrace();
	throw new RuntimeException(e);
} catch (UncheckedExecutionException e) {
	if (e.getCause() instanceof RuntimeException) {
		// Unwrap exception to match Caffeine
		throw (RuntimeException)e.getCause();
	}
	throw e;
} catch (CacheLoader.InvalidCacheLoadException e) {
	// If the entry is not found or load as null, returns null instead of an exception
	// This matches the behaviour of Caffeine
	return null;
}
```

**Comment by ben-manes** [comment]
It might be unsatisfactory, but would using Caffeine's Guava Cache adapters fit your goals? That attempts to make Caffeine conform to Guava, with similar workarounds to your snippet. Just trying to make sure you have all the options to consider, and whatever the answer will be the best choice for your project.

**Comment by vitorpamplona** [comment]
I did see those components (thank you for making them) but I discarded that approach because it adds significant complexity to the exception handling on the HAPI side. We could go there, but it wouldn't be a simple 3hr PR by then. 

HAPI was clearly coded with Caffeine's API in mind. And I do believe that, after looking at both, Caffeine's API is superior for users.

**Comment by jamesagnew** [comment]
@vitorpamplona - I want to get this merged in time for the 6.2.0 release. I've pulled these changes into a fresh PR that I'll be submitting to our internal review process tomorrow: #4196

**Comment by vitorpamplona** [comment]
Nice! Yes, let's go! :)

**Comment by vitorpamplona** [comment]
Thank you, James!

**Comment by vitorpamplona** [comment]
Hi @jamesagnew 

Is there any chance we can avoid using the caffeine library as default? Today every Android developer hits a roadblock when trying to use HAPI because they need to figure out that they need to manually remove caffeine and add guava in their build files. 

The current dependency stack doesn't provide a great dev experience for Android. :( 

CC @jingtang10 @brynrhodes @JPercival

**Comment by jamesagnew** [comment]
@vitorpamplona I thought we had? What is pulling it in?

**Comment by jamesagnew** [comment]
@vitorpamplona pushing through a fix in https://github.com/hapifhir/hapi-fhir/pull/5472

**Comment by vitorpamplona** [comment]
Thank you, James!

**Pull request closed without merging**
