### PR TITLE
Upgrade okhttp_version to 4.9.3.

### PR DESCRIPTION
**Pull request by MFAshby**
Remove dependency on okhttp.internal package.

Fixes https://github.com/hapifhir/hapi-fhir/issues/3682

### CODE REVIEW

**Comment by tadgh** [comment]
Happy to merge this once the tests all pass :) Thanks for the contribution @MFAshby

**Comment by MFAshby** [comment]
Thanks @tadgh ! Looks like the build failed so I'll see what's up with that.

**Comment by tadgh** [comment]
Looks like a test failure asserting on user agent, should be pretty easy to fix: 
https://dev.azure.com/hapifhir/HAPI%20FHIR/_build/results?buildId=7468&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=738c417a-4a48-5620-b571-4f9e77e0bfd2&l=47921.

 If you are unable to view the test results, I'll post the failure here: 

```
12:57:11,246 [ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.833 s <<< FAILURE! - in ca.uhn.fhir.android.client.GenericClientDstu3IT
12:57:11,252 [ERROR] ca.uhn.fhir.android.client.GenericClientDstu3IT.testBinaryCreateWithNoContentType  Time elapsed: 0.019 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <HAPI-FHIR/6.1.0-PRE2-SNAPSHOT (FHIR Client; FHIR 3.0.2/DSTU3; okhttp/3.8.1)> but was: <HAPI-FHIR/6.1.0-PRE2-SNAPSHOT (FHIR Client; FHIR 3.0.2/DSTU3; 4.9.3)>
	at ca.uhn.fhir.android.client.GenericClientDstu3IT.validateUserAgent(GenericClientDstu3IT.java:95)
	at ca.uhn.fhir.android.client.GenericClientDstu3IT.testBinaryCreateWithNoContentType(GenericClientDstu3IT.java:203)


```

**Comment by tadgh** [comment]
I agree it is not critical for the test. Feel free to remove it if you so desire :)

**Comment by Baterka** [comment]
I am very looking forward to this PR :)

**Comment by MFAshby** [comment]
@tadgh done, I think this is finished.

**Review by tadgh — APPROVED** [review]

**Comment by MFAshby** [comment]
@tadgh no problem! thanks very much for the review and merge.

**Pull request merged**
