### PR TITLE
Several IPS fixes

### PR DESCRIPTION
**Pull request by jamesagnew**

### CODE REVIEW

**Comment by daniellrgn** [comment]
@jamesagnew Could a fix for [this line](https://github.com/hapifhir/hapi-fhir/blob/c411789bb74a8ca78a57926ca622238e405b2e45/hapi-fhir-jpaserver-ips/src/main/resources/ca/uhn/fhir/jpa/ips/narrative/allergyintolerance.html#L33) be rolled in here as well? Thymeleaf error from AllergyIntolerances missing reaction.severity (e.g. https://fhir.ips-demo.dev.cirg.uw.edu/fhir/Patient/10953/$summary)

> HAPI-0389: Failed to call access method: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: \"item.getSeverity().toCode()\" (template: \"IpsUtilityFragments\" - line 184, col 23)

**Comment by jamesagnew** [comment]
@daniellrgn yup - i actually caught that one in a sweep i did this afternoon for potential NPEs, it's fixed in this PR

**Comment by jamesagnew** [comment]
@daniellrgn at least i think it is ... if you wanted to test on hapi.fhir.org that'd be awesome. All fixes in this PR are deployed there as of now.

**Comment by daniellrgn** [comment]
Thank you @jamesagnew , that seems to have [done the trick](https://fhir.ips-demo.dev.cirg.uw.edu/fhir/Patient/14599/$summary)!

**Review by jmarchionatto — APPROVED** [review]
Looks good! Approved

**Pull request merged**
