### PR TITLE
Added content message delivery for SubscriptionWebsocketHandler

### PR DESCRIPTION
**Pull request by ArtyomyuS**
## Description 
- This pull-request provides new support for the subscription R5 topic based to consider `content` property for the delivered messages so that if content is `IDONLY` the web socket message to contain an id, in case of `FULLREFERENCE` to consider the payload of the resource. In case of no content provided the payload remain as today: `EMPTY`. This pull-request does not affect previous FHIR versions nor any of the existing behaviour related to web socket messages.
- linked issues [5683](https://github.com/hapifhir/hapi-fhir/pull/5683) 

## Quotes about findings and assumptions
- Not sure about the content type if that shall be covered as well inside this pull-request

## Brief change log
- Updated `ca.uhn.fhir.jpa.subscription.match.deliver.websocket.SubscriptionWebsocketHandler`
- Changed the implementation for the method `handleMessage(Message<?> theMessage)`
- This pull-request doesn't not include unit tests for the new functionality. First draft review is required.

## Verifying this change
This change added tests and can be verified as follows:
- To be done after first draft review

## Documentation
- Does this pull-request introduce a new feature? Yes
- The documentation shall be part of the official one as: https://hl7.org/fhir/valueset-subscription-payload-content.html

### CODE REVIEW

**Comment by ArtyomyuS** [comment]
Hellow @jamesagnew , @fil512 , @tadgh could you please have an initial review, to confirm the pull-request is ok to be continued 👍 . Thanks

**Comment by jamesagnew** [comment]
@ArtyomyuS this approach looks good to me!

**Comment by ArtyomyuS** [comment]
Going to provide additional test 👍

**Comment by ArtyomyuS** [comment]
Hey @jamesagnew would you recommend update `BaseSubscriptionDeliverySubscriberTest` for the new changes or consider a new test class to fully support `SubscriptionWebsocketHandler`?

I challenge it as I can see the actual mocks within `BaseSubscriptionDeliverySubscriberTest` does not consider any of the `SubscriptionWebsocketHandler` implementations.

Please advice

**Comment by ArtyomyuS** [comment]
Hello @jamesagnew sorry if the question was not clear. Shall I create a new test class like: `ca.uhn.fhir.jpa.subscription.match.deliver.websocket.SubscriptionWebsocketHandlerTest`? Or shall I use an existing class for the payload content testing.

Thanks for your support.

**Comment by jamesagnew** [comment]
I would think putting a new test next to `WebsocketWithSubscriptionIdR4Test` would be the best spot - you could base your test largely on that test too

**Comment by ArtyomyuS** [comment]
Hello @jamesagnew , provided unit tests. I thought it shall be more appropriate to have them inside `hapi-fhir-jpaserver-test-r5`. Please advice if there are changes required. The pull-request is ready for review.

**Comment by jamesagnew** [comment]
Initial glance looks great! Once CI passes I'll give it a real review and get it merged. Thanks for the contribution!

**Comment by jamesagnew** [comment]
@ArtyomyuS looks like the spotless code formatting check failed. Can you run `mvn spotless:apply` and then commit+push the results to your branch?

**Comment by ArtyomyuS** [comment]
Hey @jamesagnew run the code, hopefully it works 🤞

**Comment by ArtyomyuS** [comment]
Also looking into the check pipeline it shows success: https://github.com/hapifhir/hapi-fhir/actions/runs/7906650465/job/21582427202?pr=5692#step:4:8399

**Comment by ArtyomyuS** [comment]
Hello @jamesagnew I guess we shall be fine now. Thank you

**Comment by ArtyomyuS** [comment]
Hey @jamesagnew any thought on the pull-request. Thank you for the support 🙏

**Review by jamesagnew — APPROVED** [review]

**Comment by ArtyomyuS** [comment]
Hello @jamesagnew I can see we're progressing with the pull-request, is there anything I could help more here? 💪

**Pull request merged**
