### PR TITLE
Add recursive include support for SearchParameterMap

### PR DESCRIPTION
**Pull request by vilaug**
Fixes the issue described in #3269

### CODE REVIEW

**Comment by jarimayenburg** [comment]
I would have expected a different implementation: A change to the addUrlIncludeParams function itself, where it adds _recurse to the param name for all recursive includes. That way you also catch recursive rev-includes.

**Comment by jarimayenburg** [comment]
LGTM!

**Review by jarimayenburg — APPROVED** [review]
LGTM

**Comment by jamesagnew** [comment]
Hi @vilaug - Apologies, I'm not quite sure I follow what happened with this PR but I'm pushing your commits into a new PR to merge. Fix looks good.

**Comment by vilaug** [comment]
> Hi @vilaug - Apologies, I'm not quite sure I follow what happened with this PR but I'm pushing your commits into a new PR to merge. Fix looks good.

Hey, no worries, after checking the PR and seeing the conflicts, I saw that `recurse` includes are added in a separate call in `toNormalizedQueryString()`, didn't verify further and assumed that the issue was fixed in another PR, good thing you caught it!

**Pull request closed without merging**
