### PR TITLE
Configurable submit ResourceModifiedMessage immediately if of type Subscription, store in DB on failure

### PR DESCRIPTION
**Pull request by SevcikMichal**
Trying to address #6394.

### CODE REVIEW

**Comment by jamesagnew** [comment]
The async subscription processing was added for several reasons:

- It avoids issues where the database commit fails but the message has already been placed on the subscription processing queue, so subscription processing proceeds on a resource that was never actually written to the DB successfully
- It improves scalability by batching submissions to the processing queue, which is critical for very large throughput systems

This PR undoes both of those benefits, and can't be merged as such.

Looking at your ticket, I guess part of the issue is that subscriptions take a long time to activate. Certainly I could see a world where we put changes to the Subscription resource itself on the queue immediately since subscriptions themselves are typically pretty low volume (and the activator loads from the DB I'm pretty sure, so stale data shouldn't be an issue) - this would solve that issue, although it would still leave the delays associated with resources.

I'd assume something like that, combined with a smaller polling delay (1s?) could largely remove the delays you're experiencing. If you wanted to proceed with implementing such a change, please make sure that it's configuable (via JpaStorageSettings) and includes comprehensive unit tests.

**Comment by SevcikMichal** [comment]
> The async subscription processing was added for several reasons:
> 
> * It avoids issues where the database commit fails but the message has already been placed on the subscription processing queue, so subscription processing proceeds on a resource that was never actually written to the DB successfully
> * It improves scalability by batching submissions to the processing queue, which is critical for very large throughput systems
> 
> This PR undoes both of those benefits, and can't be merged as such.
> 
> Looking at your ticket, I guess part of the issue is that subscriptions take a long time to activate. Certainly I could see a world where we put changes to the Subscription resource itself on the queue immediately since subscriptions themselves are typically pretty low volume (and the activator loads from the DB I'm pretty sure, so stale data shouldn't be an issue) - this would solve that issue, although it would still leave the delays associated with resources.
> 
> I'd assume something like that, combined with a smaller polling delay (1s?) could largely remove the delays you're experiencing. If you wanted to proceed with implementing such a change, please make sure that it's configuable (via JpaStorageSettings) and includes comprehensive unit tests.

Thanks for the explanation.
And yes even shaving off the few seconds from the subscription to get to activated would help.
Do you mean something like checking for resource type there and only submit it immediately if it's of type subscription? Condition also with a configuration in JpaStorageSettings?

I will try to implement this and provide test as well.

**Comment by SevcikMichal** [comment]
@jamesagnew I reworked it so that only subscription resource would be submitted immediately and also only if configured that way.
I moved the configuration to the SubscriptionConfiguration as this is all relevant to subscriptions does that make sense?
Would you be able to briefly look at the changes if this makes sense?
I will start implementing the tests for this.

**Comment by SevcikMichal** [comment]
Hi @jamesagnew,
I added a unit test testing the logic to submit Subscription immediately if configured to do so.

Let me know if there is anything else missing.

**Review by jamesagnew — APPROVED** [review]
Looks good to me! Thanks for the contribution!

**Comment by jamesagnew** [comment]
This is now merged, thanks again for the contribution. FYI this has unfortunately missed the code freeze for our November 7.6.0 release, so it will be available as GA in the February release (probably called 8.0.0). Snapshot builds should start to appear by tomorrow though.

**Pull request merged**
