### PR TITLE
Fix issue that OpenAPI specification had errors when validating it against Swagger/OpenAPI schema and Swagger/OpenAPI spec

### PR DESCRIPTION
**Pull request by delopst**
HAPI Fhir OpenAPI specification has errors when validating it against Swagger/OpenAPI schema and Swagger/OpenAPI spec (https://apitools.dev/swagger-parser/online/).

With this commit, validation is passing.

### CODE REVIEW

**Review by jamesagnew — APPROVED** [review]
Thanks for the contribution!

**Comment by jamesagnew** [comment]
I've marked for approval, but I do note that several OpenAPI unit tests are failing so this probably needs a bit of cleanup before it can be merged. Thanks!

**Comment by delopst** [comment]
I see. The problem was that there was already a different swagger version in the root pom.
I have consolidated them. At least locally the ServerDstu3Test that was failing before is now passing.

**Comment by delopst** [comment]
It seems like the tests are passing now.

**Pull request merged**
