### PR TITLE
#4078 Fix BinaryAccessProvider empty stream check

### LINKED ISSUE #4078: BinaryAccessProvider use of `inputstream.available()`
On https://github.com/hapifhir/hapi-fhir/blob/5b413a9135efb4acf659d2eb262a584ec4bb8d74/hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/binary/provider/BinaryAccessProvider.java#L193 the use of `inputstream.available()` may not be the best fit for what was the intention. From https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/InputStream.html#available() the `available` does 

> Returns an estimate of the number of bytes that can be read (or skipped over) from this input stream without blocking

-but isn't the operation supposed to block? We've experienced various behavior depending on the input size.

### PR DESCRIPTION
**Pull request by ttntrifork**
Fix #4078 by using a PushbackInputStream to check if the input stream is empty or not.

### CODE REVIEW

**Comment by tadgh** [comment]
This is a much nicer solution, thanks for the contribution! Once all tests pass i'm happy to merge this

**Comment by tadgh** [comment]
Not sure if you have access to this, but looks like a few tests were broken by this change (mock tests): 
https://github.com/hapifhir/hapi-fhir/pull/4170/checks?check_run_id=9014395886

If you have the time to go around and patch them, that would be appreciated. If not, I will happily take that work on, but won't be able to until next week. 

Cheers,

**Comment by ttntrifork** [comment]
I updated mocks in test `testBinaryAccessWrite_WithContentLength15`, but the other failing test `testWriteSmallAttachment` actually proves a bug in my implementation 😅 

I will look into it tomorrow!

**Comment by ttntrifork** [comment]
Alright, new failures. I have so far not being able to run mvn test on my local Windows machine with locale da-DK, so have relied on the pipeline to test for me. 

I am looking into making the mvn test run on my machine so I can run the full suite before committing.

**Comment by tadgh** [comment]
Heya, my apologies. I'm on the west coast of canada, so our timezones arent matching up. All good, LGTM is often flaky like this, we will be phasing it out shortly.

**Comment by tadgh** [comment]
@ttntrifork Are you OK with being credited in HAPI-FHIR for this change? If so, I will commit a changelog and an attribution on a separate branch. Let me know :) and we'll get this merged.

**Comment by ttntrifork** [comment]
Yeah sure, that would be great thanks!

**Review by tadgh — APPROVED** [review]

**Pull request merged**
