### PR TITLE
feat: added support for package.tgz uri in the "file:/" format

### PR DESCRIPTION
**Pull request by patrick-werner**

### CODE REVIEW

**Comment by jkiddo** [comment]
Community could really need this PR as part of the 6.0.0 release

**Comment by tadgh** [comment]
Do you mean the upcoming 5.7.0 release? if so, re-point this merge to `rel_5_7` branch and I will rush to review it and get it in. If you do indeed mean 6.0.0, then the current MR is fine, and I will review it once I get a chunk of free time.

**Comment by jkiddo** [comment]
My bad - I meant the 5.7 branch. @patrick-werner  please redirect target

**Comment by tadgh** [comment]
Also, a changelog in the 5_7_0 folder would be appreciated ! Happy to add
that myself though if you are strapped for time

**Comment by patrick-werner** [comment]
changed the target, added changelog entry @tadgh

**Comment by jkiddo** [comment]
Looks good

**Review by tadgh — APPROVED** [review]
LGTM

**Review by tadgh — APPROVED** [review]

**Comment by patrick-werner** [comment]
Thanks @tadgh !

**Pull request merged**
