### PR TITLE
Fix UnsupportedOperationException while validating MHD Document Bundle

### LINKED ISSUE #5924: UnsupportedOperationException causing validation error while validating resources based on IHE MHD implementation guide
**Describe the bug**
While validating `Bundle` resources using `https://profiles.ihe.net/ITI/MHD/StructureDefinition/IHE.MHD.Minimal.ProvideBundle` profile from IHE MHD IG (`4.2.1`), the following method from `VersionSpecificWorkerContextWrapper` is called:

```java
	@Override
	public ValueSetExpansionOutcome expandVS(
			Resource src,
			org.hl7.fhir.r5.model.ElementDefinition.ElementDefinitionBindingComponent binding,
			boolean cacheOk,
			boolean Hierarchical) {
		throw new UnsupportedOperationException(Msg.code(663));
	}
```

As a result, the following error is returned in the validation result:
```json
{
            "severity": "error",
            "code": "processing",
            "details": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/java-core-messageId",
                        "code": "SLICING_CANNOT_BE_EVALUATED"
                    }
                ]
            },
            "diagnostics": "Slicing cannot be evaluated: Problem evaluating slicing expression for element in profile https://profiles.ihe.net/ITI/MHD/StructureDefinition/IHE.MHD.Minimal.ProvideBundle|4.2.2 path Bundle.entry[2] (fhirPath = true and resource.conformsTo('http://hl7.org/fhir/StructureDefinition/Binary') and (request.method memberOf 'http://hl7.org/fhir/ValueSet/http-verb|4.0.1')): HAPI-0663: ",
            "location": [
                "Bundle.entry[2]",
                "Line[141] Col[10]"
            ]
        }
```

**To Reproduce**
1. Download IHE MHD implementation guide [here](https://profiles.ihe.net/ITI/MHD/4.2.1/package.tgz)
2. Copy and paste the following class
  ```java
import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.context.support.DefaultProfileValidationSupport;
import ca.uhn.fhir.validation.FhirValidator;
import ca.uhn.fhir.validation.ValidationResult;
import org.hl7.fhir.common.hapi.validation.support.CommonCodeSystemsTerminologyService;
import org.hl7.fhir.common.hapi.validation.support.InMemoryTerminologyServerValidationSupport;
import org.hl7.fhir.common.hapi.validation.support.NpmPackageValidationSupport;
import org.hl7.fhir.common.hapi.validation.support.SnapshotGeneratingValidationSupport;
import org.hl7.fhir.common.hapi.validation.support.ValidationSupportChain;
import org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator;

import java.io.IOException;

public class HapiFhirIheMhdValidation {

	public static void main(String[] args) throws IOException {
		var bundle = """
			{
			   	"resourceType": "Bundle",
			   	"meta": {
			   		"profile": [
			   			"https://profiles.ihe.net/ITI/MHD/StructureDefinition/IHE.MHD.Minimal.ProvideBundle"
			   		],
			   		"security": [
			   			{
			   				"system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
			   				"code": "HTEST"
			   			}
			   		]
			   	},
			   	"type": "transaction",
			   	"timestamp": "2024-05-11T14:16:19.224Z",
			   	"entry": [
			   		{
			   			"fullUrl": "urn:uuid:9649cc3d-eb0b-407b-b1ba-61c4eef4dba3",
			   			"resource": {
			   				"resourceType": "List",
			   				"id": "9649cc3d-eb0b-407b-b1ba-61c4eef4dba3",
			   				"meta": {
			   					"profile": [
			   						"https://profiles.ihe.net/ITI/MHD/StructureDefinition/IHE.MHD.Minimal.SubmissionSet"
			   					],
			   					"security": [
			   						{
			   							"system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
			   							"code": "HTEST"
			   						}
			   					]
			   				},
			   				"text": {
			   					"status": "extensions",
			   					"div": "<div xmlns=\\"http://www.w3.org/1999/xhtml\\">SubmissionSet with Patient</div>"
			   				},
			   				"contained": [
			   					{
			   						"resourceType": "Practitioner",
			   						"id": "622209e6-32ad-4283-b4eb-e2bea2aea856",
			   						"telecom": [
			   							{
			   								"system": "email",
			   								"value": "john.doe@localhost"
			   							}
			   						]
			   					}
			   				],
			   				"extension": [
			   					{
			   						"url": "https://profiles.ihe.net/ITI/MHD/StructureDefinition/ihe-sourceId",
			   						"valueIdentifier": {
			   							"value": "urn:oid:1.2.3.4"
			   						}
			   					},
			   					{
			   						"url": "https://profiles.ihe.net/ITI/MHD/StructureDefinition/ihe-intendedRecipient",
			   						"valueReference": {
			   							"reference": "#622209e6-32ad-4283-b4eb-e2bea2aea856"
			   						}
			   					}
			   				],
			   				"identifier": [
			   					{
			   						"use": "usual",
			   						"system": "urn:ietf:rfc:3986",
			   						"value": "urn:oid:1.2.840.113556.1.8000.2554.58783.21864.3474.19410.44358.58254.41281.46343"
			   					}
			   				],
			   				"status": "current",
			   				"mode": "working",
			   				"code": {
			   					"coding": [
			   						{
			   							"system": "https://profiles.ihe.net/ITI/MHD/CodeSystem/MHDlistTypes",
			   							"code": "submissionset"
			   						}
			   					]
			   				},
			   				"subject": {
			   					"reference": "urn:uuid:51eb4fab-9d1a-4314-ad7c-363fc430f52c"
			   				},
			   				"date": "2004-10-25T23:50:50-05:00",
			   				"entry": [
			   					{
			   						"item": {
			   							"reference": "urn:uuid:f494ac72-be69-4910-baf4-0cce4a45e7c1"
			   						}
			   					}
			   				]
			   			},
			   			"request": {
			   				"method": "POST",
			   				"url": "List"
			   			}
			   		},
			   		{
			   			"fullUrl": "urn:uuid:f494ac72-be69-4910-baf4-0cce4a45e7c1",
			   			"resource": {
			   				"resourceType": "DocumentReference",
			   				"id": "f494ac72-be69-4910-baf4-0cce4a45e7c1",
			   				"meta": {
			   					"profile": [
			   						"https://profiles.ihe.net/ITI/MHD/StructureDefinition/IHE.MHD.Minimal.DocumentReference"
			   					],
			   					"security": [
			   						{
			   							"system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
			   							"code": "HTEST"
			   						}
			   					]
			   				},
			   				"masterIdentifier": {
			   					"system": "urn:ietf:rfc:3986",
			   					"value": "urn:oid:1.2.840.113556.1.8000.2554.53432.348.12973.17740.34205.4355.50220.62012"
			   				},
			   				"status": "current",
			   				"subject": {
			   					"reference": "urn:uuid:51eb4fab-9d1a-4314-ad7c-363fc430f52c"
			   				},
			   				"content": [
			   					{
			   						"attachment": {
			   							"contentType": "text/plain",
			   							"url": "urn:uuid:4d14267b-19ff-4237-a301-4cdcfd67d4f9",
			   							"size": 11,
			   							"hash": "MGE0ZDU1YThkNzc4ZTUwMjJmYWI3MDE5NzdjNWQ4NDBiYmM0ODZkMA=="
			   						},
			   						"format": {
			   							"system": "http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode",
			   							"code": "urn:ihe:iti:xds-sd:text:2008"
			   						}
			   					}
			   				]
			   			},
			   			"request": {
			   				"method": "POST",
			   				"url": "DocumentReference"
			   			}
			   		},
			   		{
			   			"fullUrl": "urn:uuid:4d14267b-19ff-4237-a301-4cdcfd67d4f9",
			   			"resource": {
			   				"resourceType": "Binary",
			   				"id": "4d14267b-19ff-4237-a301-4cdcfd67d4f9",
			   				"meta": {
			   					"security": [
			   						{
			   							"system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
			   							"code": "HTEST"
			   						}
			   					]
			   				},
			   				"contentType": "text/plain",
			   				"data": "SGVsbG8gV29ybGQ="
			   			},
			   			"request": {
			   				"method": "POST",
			   				"url": "Binary"
			   			}
			   		},
			   		{
			   			"fullUrl": "urn:uuid:51eb4fab-9d1a-4314-ad7c-363fc430f52c",
			   			"resource": {
			   				"resourceType": "Patient",
			   				"id": "51eb4fab-9d1a-4314-ad7c-363fc430f52c",
			   				"meta": {
			   					"security": [
			   						{
			   							"system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
			   							"code": "HTEST"
			   						}
			   					]
			   				},
			   				"name": [
			   					{
			   						"family": "Doe",
			   						"given": [
			   							"John"
			   						]
			   					}
			   				]
			   			},
			   			"request": {
			   				"method": "POST",
			   				"url": "Patient"
			   			}
			   		}
			   	]
			   }
			""";

		FhirContext fhirContext = FhirContext.forR4();

		var validationSupport = new ValidationSupportChain();
		validationSupport.addValidationSupport(new DefaultProfileValidationSupport(fhirContext));
		validationSupport.addValidationSupport(new SnapshotGeneratingValidationSupport(fhirContext));
		validationSupport.addValidationSupport(new CommonCodeSystemsTerminologyService(fhirContext));
		validationSupport.addValidationSupport(new InMemoryTerminologyServerValidationSupport(fhirContext));

		NpmPackageValidationSupport npmPackageValidationSupport = new NpmPackageValidationSupport(fhirContext);
		npmPackageValidationSupport.loadPackageFromClasspath("classpath:package.tgz");
		validationSupport.addValidationSupport(npmPackageValidationSupport);

		var instanceValidator = new FhirInstanceValidator(validationSupport);
		FhirValidator validator = fhirContext.newValidator();
		validator.registerValidatorModule(instanceValidator);

		ValidationResult validationResult = validator.validateWithResult(bundle);
		if (validationResult.isSuccessful()) {
			System.out.println("Validation successful");
		} else {
			System.out.println("Validation failed");
			System.out.println(validationResult.getMessages());
		}
	}
  ```
3. Runs the class

**Expected behavior**
No validation error should be reported regarding the slice as the resource is valid.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 7.0.2
 - OS: MacOS/Linux
 - Browser: n/a

### PR DESCRIPTION
**Pull request by subigre**
Changelog:

- Fetch the ValueSet resource and call `expandVS(ValueSet source, boolean cacheOk, boolean Hierarchical)` method
- Add unit test and resources

Fixes #5924

### CODE REVIEW

**Comment by subigre** [comment]
Could someone from the team can retrigger the `hapifhir.hapi-fhir (module-tests hapi_fhir_jpaserver_test_r4b) ` workflow step?

The build error comes from a connection timeout to Maven central:
```
11:47:35,773 [INFO] BUILD FAILURE
Could not retrieve code analysis results - Maven run failed.
11:47:35,773 [INFO] ------------------------------------------------------------------------
11:47:35,775 [INFO] Total time:  22.767 s
11:47:35,777 [INFO] Finished at: 2024-05-11T11:47:35-04:00
11:47:35,777 [INFO] ------------------------------------------------------------------------
11:47:35,779 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project hapi-fhir-jpaserver-test-r4b: The following artifacts could not be resolved: org.junit.platform:junit-platform-engine:jar:1.9.2 (absent): Could not transfer artifact org.junit.platform:junit-platform-engine:jar:1.9.2 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.124.215] failed: Connect timed out -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project hapi-fhir-jpaserver-test-r4b: The following artifacts could not be resolved: org.junit.platform:junit-platform-engine:jar:1.9.2 (absent): Could not transfer artifact org.junit.platform:junit-platform-engine:jar:1.9.2 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.124.215] failed: Connect timed out
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)

```

**Review by jamesagnew — APPROVED** [review]
Thanks for the contribution!

**Comment by subigre** [comment]
@jamesagnew I am not sure why it failed but I just run `mvn spotless:check` on the branch and everything went well:
```
[INFO] --- spotless:2.41.1:check (default-cli) @ hapi-fhir-server-cds-hooks ---
[INFO] Spotless.Java is keeping 73 files clean - 0 needs changes to be clean, 0 were already clean, 73 were skipped because caching determined they were already clean
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for HAPI-FHIR 7.3.2-SNAPSHOT:
[INFO]
[INFO] HAPI-FHIR .......................................... SUCCESS [  1.099 s]
[INFO] HAPI FHIR - Checkstyle ............................. SUCCESS [  0.066 s]
[INFO] HAPI FHIR - Deployable Artifact Parent POM ......... SUCCESS [  0.033 s]
[INFO] HAPI FHIR BOM ...................................... SUCCESS [  0.033 s]
[INFO] HAPI FHIR - Core Library ........................... SUCCESS [  0.609 s]
[INFO] HAPI FHIR - ServiceLoaders ......................... SUCCESS [  0.031 s]
[INFO] HAPI FHIR - ServiceLoaders - Caching API ........... SUCCESS [  0.035 s]
[INFO] HAPI FHIR - ServiceLoaders - Caching Caffeine ...... SUCCESS [  0.037 s]
[INFO] HAPI FHIR - ServiceLoaders - Caching Testing ....... SUCCESS [  0.030 s]
[INFO] HAPI FHIR - Server Framework ....................... SUCCESS [  0.056 s]
[INFO] HAPI FHIR - Validation Resources (DSTU3) ........... SUCCESS [  0.031 s]
[INFO] HAPI FHIR - Client Framework ....................... SUCCESS [  0.038 s]
[INFO] HAPI FHIR Test Utilities ........................... SUCCESS [  0.037 s]
[INFO] HAPI FHIR Structures - DSTU3 ....................... SUCCESS [  0.037 s]
[INFO] HAPI FHIR - Validation Resources (FHIR R4) ......... SUCCESS [  0.030 s]
[INFO] HAPI FHIR Structures - FHIR R4 ..................... SUCCESS [  0.039 s]
[INFO] HAPI FHIR - Validation Resources (DSTU2) ........... SUCCESS [  0.029 s]
[INFO] HAPI FHIR JPA Model ................................ SUCCESS [  0.042 s]
[INFO] HAPI FHIR Structures - HL7.org DSTU2 ............... SUCCESS [  0.038 s]
[INFO] HAPI FHIR Structures - FHIR r4b .................... SUCCESS [  0.036 s]
[INFO] HAPI FHIR - Validation Resources (FHIR R5) ......... SUCCESS [  0.031 s]
[INFO] HAPI FHIR Structures - FHIR R5 ..................... SUCCESS [  0.035 s]
[INFO] HAPI Tinder Plugin ................................. SUCCESS [  0.045 s]
[INFO] HAPI FHIR Structures - DSTU2 (FHIR v1.0.0) ......... SUCCESS [  0.037 s]
[INFO] HAPI FHIR - Validation Resources DSTU2.1 (2016May) . SUCCESS [  0.029 s]
[INFO] HAPI FHIR Structures - DSTU2.1 (2016May) ........... SUCCESS [  0.034 s]
[INFO] HAPI FHIR - Converter .............................. SUCCESS [  0.035 s]
[INFO] HAPI FHIR - Validation Resources (FHIR R4B) ........ SUCCESS [  0.030 s]
[INFO] HAPI FHIR JPA Model ................................ SUCCESS [  0.035 s]
[INFO] HAPI FHIR - Validation ............................. SUCCESS [  0.037 s]
[INFO] HAPI FHIR OkHttp Client ............................ SUCCESS [  0.037 s]
[INFO] HAPI FHIR JAX-RS Server ............................ SUCCESS [  0.034 s]
[INFO] HAPI FHIR JPA - Search Parameters .................. SUCCESS [  0.036 s]
[INFO] HAPI FHIR Storage api .............................. SUCCESS [  0.053 s]
[INFO] HAPI FHIR - Master Data Management ................. SUCCESS [  0.044 s]
[INFO] HAPI FHIR Subscription Server ...................... SUCCESS [  0.040 s]
[INFO] HAPI FHIR Server - SQL Migration ................... SUCCESS [  0.037 s]
[INFO] HAPI FHIR JPA Server - Batch2 Task Processor ....... SUCCESS [  0.040 s]
[INFO] hapi-fhir-storage-batch2-jobs ...................... SUCCESS [  0.035 s]
[INFO] hapi-fhir-server-openapi ........................... SUCCESS [  0.031 s]
[INFO] HAPI FHIR JPA Server ............................... SUCCESS [  0.055 s]
[INFO] HAPI FHIR JPA Server - HFQL Driver ................. SUCCESS [  0.034 s]
[INFO] HAPI FHIR TestPage Overlay ......................... SUCCESS [  0.039 s]
[INFO] HAPI FHIR - Docs ................................... SUCCESS [  0.033 s]
[INFO] hapi-fhir-storage-test-utilities ................... SUCCESS [  0.030 s]
[INFO] HAPI FHIR JPA Server Test Utilities ................ SUCCESS [  0.038 s]
[INFO] HAPI FHIR JPA Server Test Dstu2 .................... SUCCESS [  0.031 s]
[INFO] HAPI FHIR JPA Server Test Dstu3 .................... SUCCESS [  0.031 s]
[INFO] HAPI FHIR JPA Server - Batch2 specification tests .. SUCCESS [  0.030 s]
[INFO] HAPI FHIR JPA Server Test R4 ....................... SUCCESS [  0.038 s]
[INFO] HAPI FHIR JPA Server Test R4B ...................... SUCCESS [  0.029 s]
[INFO] HAPI FHIR JPA Server Test R5 ....................... SUCCESS [  0.031 s]
[INFO] HAPI FHIR JPA Server Elastic Test Utilities ........ SUCCESS [  0.030 s]
[INFO] HAPI Tinder Plugin - Test Project .................. SUCCESS [  0.037 s]
[INFO] HAPI FHIR - ServiceLoaders - Caching Guava ......... SUCCESS [  0.030 s]
[INFO] HAPI FHIR - Clinical Reasoning ..................... SUCCESS [  0.035 s]
[INFO] hapi-fhir-storage-mdm .............................. SUCCESS [  0.031 s]
[INFO] HAPI FHIR JPA Server - International Patient Summary (IPS) SUCCESS [  0.032 s]
[INFO] HAPI FHIR JPA Server - Master Data Management ...... SUCCESS [  0.040 s]
[INFO] HAPI FHIR - fhirtest.uhn.ca Deployable WAR ......... SUCCESS [  0.045 s]
[INFO] HAPI FHIR - Android ................................ SUCCESS [  0.036 s]
[INFO] HAPI FHIR - Command Line Client - API .............. SUCCESS [  0.036 s]
[INFO] HAPI FHIR - Command Line Client - Base Project ..... SUCCESS [  0.033 s]
[INFO] HAPI FHIR - Command Line Client - Application ...... SUCCESS [  0.041 s]
[INFO] HAPI FHIR - Distribution Archive ................... SUCCESS [  0.033 s]
[INFO] HAPI FHIR JAX-RS Server Kotlin test ................ SUCCESS [  0.039 s]
[INFO] HAPI FHIR - Minimal Dependency Test - Client ....... SUCCESS [  0.030 s]
[INFO] HAPI FHIR - Minimal Dependency Test - Server ....... SUCCESS [  0.029 s]
[INFO] hapi-fhir-spring-boot-autoconfigure ................ SUCCESS [  0.030 s]
[INFO] hapi-fhir-spring-boot-starter ...................... SUCCESS [  0.028 s]
[INFO] hapi-fhir-spring-boot .............................. SUCCESS [  0.026 s]
[INFO] hapi-fhir-spring-boot-samples ...................... SUCCESS [  0.028 s]
[INFO] hapi-fhir-spring-boot-sample-client-apache ......... SUCCESS [  0.032 s]
[INFO] hapi-fhir-spring-boot-sample-client-okhttp ......... SUCCESS [  0.029 s]
[INFO] hapi-fhir-spring-boot-sample-server-jersey ......... SUCCESS [  0.029 s]
[INFO] HAPI FHIR - JaCoCo Test Coverage ................... SUCCESS [  0.030 s]
[INFO] HAPI FHIR - CDS Hooks .............................. SUCCESS [  0.036 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.958 s
[INFO] Finished at: 2024-05-15T19:07:22+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jamesagnew** [comment]
@subigre that is a false negative - because of some weird permissions issues we haven't yet figured out, external PRs always fail that check. Thanks again!

**Pull request merged**
